env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
  no-case-declarations: 0
  no-constant-condition:
    - error
    - checkLoops: false
  sort-imports:
    - error
  prefer-const:
    - error
    - destructuring: all
  no-var:
    - error
  array-bracket-spacing:
    - error
    - always
    - singleValue: false
  block-spacing:
    - error
  brace-style:
    - error
  comma-dangle:
    - error
    - only-multiline
  object-curly-spacing:
    - error
    - always
  computed-property-spacing:
    - error
    - never
  react/jsx-sort-prop-types:
    - off
